Import('*')

_myName = 'libavsconf'
_env = env.Clone()
#_env.Append(CPPFLAGS = "-DOS_PATH_SEPARATOR=\"'/'\" ")
_env.Append(CPPPATH = ['#include', 
			'#system/include', 
			'#libvideo/', 
			'#libnet/include', 
			'#libaux/include', 
			'#libckits/include',
                        '#libfoundation/include'])
#_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl','foundation']

totalSources = '''
    IMultiParty.cpp \
    CompoundMix.cpp \
    AudioConfMix.cpp \
    VideoConfMix.cpp \
    WaitingRoom.cpp \
    MOHPlayer.cpp\
    mixfunc.c
'''
#mix_assembly.s
#all = _env.StaticLibrary('libavsconf.a', totalSources.split())
#all = _env.SharedLibrary('libavsconf.so', totalSources.split(), _LIBFLAGS=' -Wl,-Bsymbolic')

objs = totalSources.split()
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)



#target = _env.Command(_myName + '.so', _myName + '.so-dev', "$STRIP -g $SOURCE -o $TARGET")
#objs.append(target)


Return('target')
